# Generated by Django 5.2.4 on 2025-07-16 18:10

import django.db.models.deletion
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=video.models.video_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('final_validated', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('posture_score', models.FloatField(blank=True, null=True)),
                ('voice_clarity_score', models.FloatField(blank=True, null=True)),
                ('facial_expression_score', models.FloatField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
